// Language Settings
const SUPPORTED_LANGUAGES = ['en', 'de', 'es', 'fr'];
const DEFAULT_LANGUAGE = 'de';

// Calendar Settings
const DEFAULT_MONTHS_AHEAD = 12;
const DEFAULT_REMINDER_METHOD = 'popup';
const DEFAULT_INDIVIDUAL_REMINDER_MINUTES = 1440; // 24 hours
const DEFAULT_SUMMARY_REMINDER_MINUTES = 5760;    // 4 days

// API Settings
const API_BATCH_SIZE = 20;
const API_RETRY_DELAY_BASE = 2000;  // Base delay in milliseconds
const API_MAX_RETRIES = 3;
const API_RATE_LIMIT_DELAY = 500;   // Delay between batches in milliseconds

// Event Settings
const EVENT_TITLE_PREFIX = '🎂';
const EVENT_SUMMARY_TITLE_PREFIX = '🎉🎂';
const EVENT_SUMMARY_TITLE_SUFFIX = '🎂🎉';

module.exports = {
    SUPPORTED_LANGUAGES,
    DEFAULT_LANGUAGE,
    DEFAULT_MONTHS_AHEAD,
    DEFAULT_REMINDER_METHOD,
    DEFAULT_INDIVIDUAL_REMINDER_MINUTES,
    DEFAULT_SUMMARY_REMINDER_MINUTES,
    API_BATCH_SIZE,
    API_RETRY_DELAY_BASE,
    API_MAX_RETRIES,
    API_RATE_LIMIT_DELAY,
    EVENT_TITLE_PREFIX,
    EVENT_SUMMARY_TITLE_PREFIX,
    EVENT_SUMMARY_TITLE_SUFFIX
};